; -------------------------------------------------------------------
;   NanoClock config file.
;   Canonical location: .adds/nanoclock/nanoclock.ini
; -------------------------------------------------------------------

[global]
;
; To uninstall, set to true
;
uninstall=false

;
; To temporarily stop displaying the clock, set to true
;
stop=false

;
; To debug, set to true
;; NOTE: Everything is sent to the syslog, to look specifically for nanoclock entries, run
;;       logread | grep '\(nanoclock\|nanoclock\.sh\)\[[[:digit:]]\+\]'
;; NOTE: Alternatively, you can find a NickelMenu config that will dump it in .adds/nanoclock/nanoclock.log
;;       over here: https://github.com/NiLuJe/NanoClock/blob/master/config/nm_nanoclock
;
debug=false

;
; If this is enabled, the current log will be dumped to .adds/nanoclock/nanoclock.log
; every time this config file is reloaded.
; This is a poor man's hack to get at the logs when you truly have no other way...
;
dump_log=false


[display]
;
; Date format string (see 'man strftime', e.g., <https://man7.org/linux/man-pages/man3/strftime.3.html>)
;
;; In addition may also use {month}, {day}, {battery}.
;; (Look for battery and locale settings further below).
;
format=%a %b %d %H:%M

;
; In addition to the usual "as necessary" refreshes,
; also refresh the clock automatically, every minute, on the dot.
; Set to false to disable.
;
autorefresh=true


;
; Where to print the clock
;

;
; With one of the embedded bitmap fonts:
;
column=0
row=0
;; ^NOTE: Can be negative (f.g., row -1 is the last line of the screen (bottom), column -1 is the last column on the screen (right)).
offset_x=0
offset_y=0
;; ^NOTE: These do *NOT* override row/column, they *fine-tune* them. Offsets can be negative, but will not wrap around edges.
;;       f.g., if you only print a %H:%M timestamp, that's 5 characters, so, the bottom-right corner of the screen would be:
;;       column=-5
;;       row=-1
;;       You can then adjust that a bit, by, say, moving it 10 pixels higher:
;;       offset_y=-10
;;  NOTE: While column/row won't, offset_x/offset_y *can* push content off-screen!

;
; Font:  (IBM, UNSCII, ALT, THIN, FANTASY, MCR, TALL, BLOCK,
;         LEGGIE, VEGGIE, KATES, FKP, CTRLD, ORP, ORPB, ORPI,
;         SCIENTIFICA, SCIENTIFICAB, SCIENTIFICAI, TERMINUS,
;         TERMINUSB, FATTY, SPLEEN, TEWI, TEWIB, TOPAZ,
;         MICROKNIGHT, VGA, COZETTE)
;
font=IBM

;
; Font Size:
; NOTE: This is an integer multiplier of the native cell size of the font. (0 means choose a sensible default based on DPI, ranging from 2 to 4).
;
size=0

;
; Color: (BLACK GRAY{1-9A-E} WHITE)
;
fg_color=BLACK
bg_color=WHITE
;

;
; With your own vector (TrueType, OpenType) fonts:
;
;; For fonts inside the same folder as your NanoClock configuration:
;;     truetype=yourfont.ttf
;
;; For fonts stored elsewhere in the filesystem:
;;     truetype=/mnt/onboard/fonts/something.ttf
;
;; Only set these if you use *italic*, **bold**, ***bold italic*** in your format string:
;;
;;     truetype_format=*%a* **%b** ***%d*** %H:%M
;;     truetype_bold=yourfont-bold.ttf
;;     truetype_italic=yourfont-italic.ttf
;;     truetype_bolditalic=yourfont-bolditalic.ttf
;
;; Technically, this can also be used for completely different font styles,
;; instead of italic or bold variants of the same font.
;
;; NOTE: Will fall back to regular mode when font file is unavailable.
;;       (e.g. while the device is connected to USB)
;
truetype_size=16.0
truetype_px=0
;; ^NOTE: size is in pt, px is in pixels. If set to non-zero, px takes precedence.
;;        In case you ever need to do the maths yourself, px = dpi / 72.0 * pt
truetype_x=0
truetype_y=0
;; ^NOTE: Much like above, these can be negative, in which case they count backwards from the opposite edge (like column/row).
;;        f.g., a rough match to the column/row example above might be:
;;        truetype_x=-115
;;        truetype_y=-44
;;
;; NOTE:  If you want to position your clock near the bottom or right edge,
;;        using negative values is the only sensible way to have it actually work in both Portrait and Landscape orientations,
;;        whether you're using a vector or a bitmap font.
;;
truetype_fg=BLACK
truetype_bg=WHITE

;
; TrueType padding
;
;; TrueType padding helps prevent visual fragments to appear,
;; in the extremely rare instance of multiple clock updates on the same page,
;; but it comes at the cost of adding extra whitespace.
;; Set to true to enable.
;; NOTE: If you still have this enabled, and you're seeing weird layout issues on the first update after a truetype switch,
;;       try disabling it.
;; NOTE: This setting is mostly meaningless if backgroundless or overlay are enabled, but it is still honored,
;;       as it might help the autorefresh magic behave seamlessly ;).
;
truetype_padding=false

;
; Misc display tweaks (regardless of the font type)
;
;; Don't render background pixels *at all* (i.e., no background "box").
;; Set to true to enable.
backgroundless=false
;; Ignores the specified foreground color, and instead use the inverse of what's on the screen.
;; (f.g., if a pixel replaces a white pixel, it'll be painted black).
;; Like with backgroundless, background pixels won't be rendered. Takes precedence over backgroundless.
;; Set to true to enable.
overlay=false
;; ^NOTE: If autorefresh is enabled, magic will happen to make these two behave without visual glitches ;).

;
; Battery percentage value (0-100)
;
;; Use {battery} in the format string.
;
;; Will only be used if the battery is between min max.
;; Default: only shown when battery level drops to 50% and under.
battery_min=0
battery_max=50
;
battery_shown_pattern=%d%%
battery_hidden_pattern=

;
; Localization (translate Month and Day names)
;
;; Set day names, Monday -> Sunday (7 words)
;; Use {day} in the format string to use this.
;
;days=Mon Tue Wed Thu Fri Sat Sun
;
;; Set month names, January -> December (12 words)
;; Use {month} in the format string to use this.
;
;months=Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
;

;
; Frontlight percentage value (0-100 or -1)
;
;; Use {frontlight} in the format string.
;; ^NOTE: It might take a couple pages to sync up on older devices (< Mk. 7). That's perfectly normal.
;
frontlight_pattern=%d%%
